namespace DALNetCore.Models
{
    public partial class BrowserLog
    {
        public long BrowserLogId { get; set; }
        public bool? ActiveXcontrols { get; set; }
        public bool? Aol { get; set; }
        public bool? BackgroundSounds { get; set; }
        public bool? Beta { get; set; }
        public string Browser { get; set; }
        public bool? CanCombineFormsInDeck { get; set; }
        public bool? CanInitiateVoiceCall { get; set; }
        public bool? CanRenderAfterInputOrSelectElement { get; set; }
        public bool? CanRenderEmptySelects { get; set; }
        public bool? CanRenderInputAndSelectElementsTogether { get; set; }
        public bool? CanRenderMixedSelects { get; set; }
        public bool? CanRenderOneventAndPrevElementsTogether { get; set; }
        public bool? CanRenderPostBackCards { get; set; }
        public bool? CanRenderSetvarZeroWithMultiSelectionList { get; set; }
        public bool? CanSendMail { get; set; }
        public bool? Cdf { get; set; }
        public string ClrVersion { get; set; }
        public bool? Cookies { get; set; }
        public bool? Crawler { get; set; }
        public int? DefaultSubmitButtonLimit { get; set; }
        public string EcmaScriptVersion { get; set; }
        public bool? Frames { get; set; }
        public int? GatewayMajorVersion { get; set; }
        public double? GatewayMinorVersion { get; set; }
        public string GatewayVersion { get; set; }
        public bool? HasBackButton { get; set; }
        public bool? HidesRightAlignedMultiselectScrollbars { get; set; }
        public string Id { get; set; }
        public string InputType { get; set; }
        public bool? IsColor { get; set; }
        public bool? IsMobileDevice { get; set; }
        public bool? JavaApplets { get; set; }
        public string JscriptVersion { get; set; }
        public int? MajorVersion { get; set; }
        public int? MaximumHrefLength { get; set; }
        public int? MaximumRenderedPageSize { get; set; }
        public int? MaximumSoftkeyLabelLength { get; set; }
        public double? MinorVersion { get; set; }
        public string MinorVersionString { get; set; }
        public string MobileDeviceManufacturer { get; set; }
        public string MobileDeviceModel { get; set; }
        public string MsdomVersion { get; set; }
        public string NumberOfSoftkeys { get; set; }
        public string Platform { get; set; }
        public string PreferredImageMime { get; set; }
        public string PreferredRenderingMime { get; set; }
        public string PreferredRenderingType { get; set; }
        public string PreferredRequestEncoding { get; set; }
        public string PreferredResponseEncoding { get; set; }
        public bool? RendersBreakBeforeWmlSelectAndInput { get; set; }
        public bool? RendersBreaksAfterHtmlLists { get; set; }
        public bool? RendersBreaksAfterWmlAnchor { get; set; }
        public bool? RendersBreaksAfterWmlInput { get; set; }
        public bool? RendersWmlDoAcceptsInline { get; set; }
        public bool? RendersWmlSelectsAsMenuCards { get; set; }
        public string RequiredMetaTagNameValue { get; set; }
        public bool? RequiresAttributeColonSubstitution { get; set; }
        public bool? RequiresContentTypeMetaTag { get; set; }
        public bool? RequiresControlStateInSession { get; set; }
        public bool? RequiresDbcscharacter { get; set; }
        public bool? RequiresHtmlAdaptiveErrorReporting { get; set; }
        public bool? RequiresLeadingPageBreak { get; set; }
        public bool? RequiresNoBreakInFormatting { get; set; }
        public bool? RequiresOutputOptimization { get; set; }
        public bool? RequiresPhoneNumbersAsPlainText { get; set; }
        public bool? RequiresSpecialViewStateEncoding { get; set; }
        public bool? RequiresUniqueFilePathSuffix { get; set; }
        public bool? RequiresUniqueHtmlCheckboxNames { get; set; }
        public bool? RequiresUniqueHtmlInputNames { get; set; }
        public bool? RequiresUrlEncodedPostfieldValues { get; set; }
        public int? ScreenBitDepth { get; set; }
        public int? ScreenCharactersHeight { get; set; }
        public int? ScreenCharactersWidt { get; set; }
        public int? ScreenPixelsHeight { get; set; }
        public int? ScreenPixelsWidth { get; set; }
        public bool? SupportsAccesskeyAttribute { get; set; }
        public bool? SupportsBodyColor { get; set; }
        public bool? SupportsBold { get; set; }
        public bool? SupportsCacheControlMetaTag { get; set; }
        public bool? SupportsCallback { get; set; }
        public bool? SupportsCss { get; set; }
        public bool? SupportsDivAlign { get; set; }
        public bool? SupportsDivNoWrap { get; set; }
        public bool? SupportsEmptyStringInCookieValue { get; set; }
        public bool? SupportsFontColor { get; set; }
        public bool? SupportsFontName { get; set; }
        public bool? SupportsFontSize { get; set; }
        public bool? SupportsImageSubmit { get; set; }
        public bool? SupportsImodeSymbols { get; set; }
        public bool? SupportsInputIstyle { get; set; }
        public bool? SupportsInputMode { get; set; }
        public bool? SupportsItalic { get; set; }
        public bool? SupportsJphoneMultiMediaAttribute { get; set; }
        public bool? SupportsJphoneSymbols { get; set; }
        public bool? SupportsQueryStringInFormAction { get; set; }
        public bool? SupportsRedirectWithCookie { get; set; }
        public bool? SupportsSelectMultiple { get; set; }
        public bool? SupportsUncheck { get; set; }
        public bool? SupportsXmlHttp { get; set; }
        public bool? Tables { get; set; }
        public string Type { get; set; }
        public bool? UseOptimizedCacheKey { get; set; }
        public bool? Vbscript { get; set; }
        public string Version { get; set; }
        public string W3cdomVersion { get; set; }
        public bool? Win16 { get; set; }
        public bool? Win32 { get; set; }
    }
}
